services:
  - type: web
    name: feedback-app-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: feedback-db
    plan: free
